# Generated by Django 4.0.5 on 2022-10-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_appointment_meeting_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_at',
            field=models.DateTimeField(unique=True),
        ),
    ]
